### ISSUE TITLE
Error using nvdia-docker

### ISSUE THREAD

**Issue by danperazzo** [Fyusion/LLFF#11]
Hello. I am trying to get the results as displayed but when I execute `sudo nvidia-docker run --rm --volume /:/host --workdir /host$PWD tf_colmap bash demo.sh` the docker returns a error. Below is the error that I have encountered:
`docker: Error response from daemon: OCI runtime create failed: container_linux.go:345: starting container process caused "process_linux.go:430: container init caused \"process_linux.go:413: running prestart hook 1 caused \\\"error running hook: exit status 1, stdout: , stderr: exec command: [/usr/bin/nvidia-container-cli --load-kmods configure --ldconfig=@/sbin/ldconfig.real --device=all --compute --utility --require=cuda>=10.0 brand=tesla,driver>=384,driver<385 brand=tesla,driver>=410,driver<411 --pid=7506 /var/lib/docker/overlay2/74b368071c67140593255d9461eb525598dbbca0ab382047da530356351746c6/merged]\\\\nnvidia-container-cli: requirement error: unsatisfied condition: brand = tesla\\\\n\\\"\"": unknown.`

**Comment by bmild** [comment]
Based on some quick googling it sounds like it might be a driver error. What GPU are you using and what version of the nvidia drivers (should be in top left if you run `nvidia-smi` command)?

The docker container is trying to run a CUDA 10.0 image. Based on the driver requirements for CUDA 10.0 from this table, looks like you need nvidia drivers >= 410.48.
https://github.com/NVIDIA/nvidia-docker/wiki/CUDA#requirements

Your problem looks similar to these ones, if you need more information to debug.
https://github.com/NVIDIA/nvidia-docker/issues/861
https://github.com/NVIDIA/nvidia-docker/issues/931

Hope that helps!

**Comment by danperazzo** [comment]
Thanks!!

**Comment by bmild** [comment]
Hmm interesting. What GPU are you using?

Were the MPIs correctly generated and saved in the folder `data/testscene/mpis_360`? Check for the file `data/testscene/mpis_360/mpi19/mpi.b`. If not, the renderer will definitely segfault and the issue was with generating the MPIs.

If the MPIs do exist, maybe there was not enough GPU memory for the renderer. It requires about 800MB. You could try ensuring this memory is available, then running the renderer command by itself in the docker env, like this (copy+paste as a single command in terminal)
`sudo nvidia-docker run --rm --volume /:/host --workdir /host$PWD tf_colmap cuda_renderer/cuda_renderer data/testscene/mpis_360 data/testscene/outputs/test_path.txt data/testscene/outputs/test_vid.mp4 360 .8 18`

**Comment by danperazzo** [comment]
Hello, 
I have just verified the output and It could not generate any MPIs. The full output is this:
`Don't need to run COLMAP
Post-colmap
('Cameras', 5)
('Images #', 20)
('Points', (9885, 3), 'Visibility', (9885, 20))
('Depth stats', 15.138568613445855, 119.2932664480696, 30.44199204545349)
Done with imgs2poses
2019-07-30 17:02:46.297945: I tensorflow/core/platform/cpu_feature_guard.cc:141] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2 FMA
2019-07-30 17:02:46.389582: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:998] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2019-07-30 17:02:46.389956: I tensorflow/compiler/xla/service/service.cc:150] XLA service 0x7079b80 executing computations on platform CUDA. Devices:
2019-07-30 17:02:46.389979: I tensorflow/compiler/xla/service/service.cc:158]   StreamExecutor device (0): GeForce GTX 1050 Ti, Compute Capability 6.1
2019-07-30 17:02:46.411227: I tensorflow/core/platform/profile_utils/cpu_utils.cc:94] CPU Frequency: 2808000000 Hz
2019-07-30 17:02:46.412082: I tensorflow/compiler/xla/service/service.cc:150] XLA service 0x70e2680 executing computations on platform Host. Devices:
2019-07-30 17:02:46.412111: I tensorflow/compiler/xla/service/service.cc:158]   StreamExecutor device (0): <undefined>, <undefined>
2019-07-30 17:02:46.412255: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1433] Found device 0 with properties: 
name: GeForce GTX 1050 Ti major: 6 minor: 1 memoryClockRate(GHz): 1.62
pciBusID: 0000:01:00.0
totalMemory: 3.95GiB freeMemory: 3.65GiB
2019-07-30 17:02:46.412274: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1512] Adding visible gpu devices: 0
2019-07-30 17:02:46.413296: I tensorflow/core/common_runtime/gpu/gpu_device.cc:984] Device interconnect StreamExecutor with strength 1 edge matrix:
2019-07-30 17:02:46.413314: I tensorflow/core/common_runtime/gpu/gpu_device.cc:990]      0 
2019-07-30 17:02:46.413321: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1003] 0:   N 
2019-07-30 17:02:46.413395: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1115] Created TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:0 with 3441 MB memory) -> physical GPU (device: 0, name: GeForce GTX 1050 Ti, pci bus id: 0000:01:00.0, compute capability: 6.1)

WARNING: The TensorFlow contrib module will not be included in TensorFlow 2.0.
For more information, please see:
  * https://github.com/tensorflow/community/blob/master/rfcs/20180907-contrib-sunset.md
  * https://github.com/tensorflow/addons
If you depend on functionality not listed there, please file an issue.

('factor/width/height args:', [None, None, 360])
('Loaded image data', (360, 480, 3, 20), array([360.        , 480.        , 395.73775333]))
Creating session
('Restoring from', './checkpoints/papermodel/checkpoint')
Traceback (most recent call last):
  File "imgs2mpis.py", line 82, in <module>
    args.numplanes, args.no_mpis, True, args.psvs)
  File "imgs2mpis.py", line 44, in gen_mpis
    ibr_runner.load_graph(logdir)
  File "/host/home/daniel/LLFF/llff/inference/mpi_tester.py", line 112, in load_graph
    self.saver = tf.train.import_meta_graph(ckpt_path + '.meta')
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/training/saver.py", line 1435, in import_meta_graph
    meta_graph_or_file, clear_devices, import_scope, **kwargs)[0]
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/training/saver.py", line 1447, in _import_meta_graph_with_return_elements
    meta_graph_def = meta_graph.read_meta_graph_file(meta_graph_or_file)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/framework/meta_graph.py", line 633, in read_meta_graph_file
    raise IOError("File %s does not exist." % filename)
IOError: File ./checkpoints/papermodel/checkpoint.meta does not exist.
mkdir: cannot create directory 'data/testscene/outputs/': File exists
('Path components', [False, False, False, False, True])
('Saved to', 'data/testscene/outputs/test_path.txt')
make: 'cuda_renderer' is up to date.
Loading data/testscene/mpis_360
loading 0 mpis
0 x 0
0 0 0 0
Big request (host) 0 MB
Successfully loaded 0 mpis
Mallocing
Big request 0 MB
Memcpying
Initializing on device
Done
Begin render poses
Loading render poses: data/testscene/outputs/test_path.txt, 120
4032 x 3024, 3324.2
Alloc video buffer on GPU 37 MB
Render frames
demo.sh: line 24:    86 Segmentation fault      (core dumped) cuda_renderer/cuda_renderer data/testscene/mpis_360 data/testscene/outputs/test_path.txt data/testscene/outputs/test_vid.mp4 360 .8 18
`

**Comment by danperazzo** [comment]
Hello, I Have just checked and It did not generate any MPI's. Below is the full output.
`Post-colmap
('Cameras', 5)
('Images #', 20)
('Points', (9885, 3), 'Visibility', (9885, 20))
('Depth stats', 15.138568613445855, 119.2932664480696, 30.44199204545349)
Done with imgs2poses
2019-07-30 17:02:46.297945: I tensorflow/core/platform/cpu_feature_guard.cc:141] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2 FMA
2019-07-30 17:02:46.389582: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:998] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2019-07-30 17:02:46.389956: I tensorflow/compiler/xla/service/service.cc:150] XLA service 0x7079b80 executing computations on platform CUDA. Devices:
2019-07-30 17:02:46.389979: I tensorflow/compiler/xla/service/service.cc:158]   StreamExecutor device (0): GeForce GTX 1050 Ti, Compute Capability 6.1
2019-07-30 17:02:46.411227: I tensorflow/core/platform/profile_utils/cpu_utils.cc:94] CPU Frequency: 2808000000 Hz
2019-07-30 17:02:46.412082: I tensorflow/compiler/xla/service/service.cc:150] XLA service 0x70e2680 executing computations on platform Host. Devices:
2019-07-30 17:02:46.412111: I tensorflow/compiler/xla/service/service.cc:158]   StreamExecutor device (0): <undefined>, <undefined>
2019-07-30 17:02:46.412255: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1433] Found device 0 with properties: 
name: GeForce GTX 1050 Ti major: 6 minor: 1 memoryClockRate(GHz): 1.62
pciBusID: 0000:01:00.0
totalMemory: 3.95GiB freeMemory: 3.65GiB
2019-07-30 17:02:46.412274: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1512] Adding visible gpu devices: 0
2019-07-30 17:02:46.413296: I tensorflow/core/common_runtime/gpu/gpu_device.cc:984] Device interconnect StreamExecutor with strength 1 edge matrix:
2019-07-30 17:02:46.413314: I tensorflow/core/common_runtime/gpu/gpu_device.cc:990]      0 
2019-07-30 17:02:46.413321: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1003] 0:   N 
2019-07-30 17:02:46.413395: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1115] Created TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:0 with 3441 MB memory) -> physical GPU (device: 0, name: GeForce GTX 1050 Ti, pci bus id: 0000:01:00.0, compute capability: 6.1)

WARNING: The TensorFlow contrib module will not be included in TensorFlow 2.0.
For more information, please see:
  * https://github.com/tensorflow/community/blob/master/rfcs/20180907-contrib-sunset.md
  * https://github.com/tensorflow/addons
If you depend on functionality not listed there, please file an issue.

('factor/width/height args:', [None, None, 360])
('Loaded image data', (360, 480, 3, 20), array([360.        , 480.        , 395.73775333]))
Creating session
('Restoring from', './checkpoints/papermodel/checkpoint')
Traceback (most recent call last):
  File "imgs2mpis.py", line 82, in <module>
    args.numplanes, args.no_mpis, True, args.psvs)
  File "imgs2mpis.py", line 44, in gen_mpis
    ibr_runner.load_graph(logdir)
  File "/host/home/daniel/LLFF/llff/inference/mpi_tester.py", line 112, in load_graph
    self.saver = tf.train.import_meta_graph(ckpt_path + '.meta')
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/training/saver.py", line 1435, in import_meta_graph
    meta_graph_or_file, clear_devices, import_scope, **kwargs)[0]
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/training/saver.py", line 1447, in _import_meta_graph_with_return_elements
    meta_graph_def = meta_graph.read_meta_graph_file(meta_graph_or_file)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/framework/meta_graph.py", line 633, in read_meta_graph_file
    raise IOError("File %s does not exist." % filename)
IOError: File ./checkpoints/papermodel/checkpoint.meta does not exist.
mkdir: cannot create directory 'data/testscene/outputs/': File exists
('Path components', [False, False, False, False, True])
('Saved to', 'data/testscene/outputs/test_path.txt')
make: 'cuda_renderer' is up to date.
Loading data/testscene/mpis_360
loading 0 mpis
0 x 0
0 0 0 0
Big request (host) 0 MB
Successfully loaded 0 mpis
Mallocing
Big request 0 MB
Memcpying
Initializing on device
Done
Begin render poses
Loading render poses: data/testscene/outputs/test_path.txt, 120
4032 x 3024, 3324.2
Alloc video buffer on GPU 37 MB
Render frames
demo.sh: line 24:    86 Segmentation fault      (core dumped) cuda_renderer/cuda_renderer data/testscene/mpis_360 data/testscene/outputs/test_path.txt data/testscene/outputs/test_vid.mp4 360 .8 18`

**Comment by danperazzo** [comment]
Hello, I have just checked and It did not render any MPIs

**Comment by bmild** [comment]
I saw in the error you posted:
`IOError: File ./checkpoints/papermodel/checkpoint.meta does not exist.`
Did you download the trained checkpoint (using `bash download_data.sh`)?

**Comment by danperazzo** [comment]
I have just checked and I have this file on my project(checkpoint.meta). I have just checked and, apparently, there was error with the tensorflow: 

2019-07-31 14:24:09.655268: W tensorflow/core/framework/op_kernel.cc:1401] OP_REQUIRES failed at conv_ops_3d.cc:332 : Resource exhausted: OOM when allocating tensor with shape[1,32,360,480,32] and type float on /job:localhost/replica:0/task:0/device:GPU:0 by allocator GPU_0_bfc
Traceback (most recent call last):
  File "imgs2mpis.py", line 82, in <module>
    args.numplanes, args.no_mpis, True, args.psvs)
  File "imgs2mpis.py", line 53, in gen_mpis
    mpis = run_inference(imgs, poses, mpi_bds, ibr_runner, num_planes, patched, disps=disps, psvs=psvs)
  File "/host/home/daniel/LLFF/llff/inference/mpi_utils.py", line 156, in run_inference
    mpi.generate(generator, num_planes)
  File "/host/home/daniel/LLFF/llff/inference/mpi_utils.py", line 55, in generate

**Comment by danperazzo** [comment]
Well, I have just discovered that there was insuficient GPU memory. My GPU has 4GB. How much memory you had?

**Comment by bmild** [comment]
Ah yeah that's it - I always use GPUs with at least 8GB.

You should be able to make it run with 4GB by changing [this line](https://github.com/Fyusion/LLFF/blob/master/imgs2mpis.py#L46) to `patched = True` (this will make the network compute the output in smaller patches).
And then by changing the argument `valid=270` in [this line](https://github.com/Fyusion/LLFF/blob/master/llff/inference/mpi_utils.py#L136) to `valid=120` (this controls the width/height of the patch computed by the network).

These two changes make the demo.sh run using only about 2.4GB on my GPU.

**Comment by danperazzo** [comment]
Alright, thanks a lot!!!! It worked :)) Those changes affect only the processing time or it impacts the final result?

**Comment by bmild** [comment]
Great! It will only slow down the time, results should be the same.

**Comment by danperazzo** [comment]
Alright, thanks!!!
