### ISSUE TITLE
Post Colmap error | sparse folder empty

### ISSUE THREAD

**Issue by 3ventHoriz0n** [Fyusion/LLFF#37]
I'm getting the following error:

Traceback (most recent call last):
File "imgs2poses.py", line 18, in 
gen_poses(args.scenedir, args.match_type)
File "/content/LLFF/llff/poses/pose_utils.py", line 274, in gen_poses
poses, pts3d, perm = load_colmap_data(basedir)
File "/content/LLFF/llff/poses/pose_utils.py", line 14, in load_colmap_data
camdata = read_model.read_cameras_binary(camerasfile)
File "/content/LLFF/llff/poses/colmap_read_model.py", line 115, in read_cameras_binary
with open(path_to_model_file, "rb") as fid:
FileNotFoundError: [Errno 2] No such file or directory: '/content/drive/My Drive/nerf_pl/mug_for_nerf/sparse/0/cameras.bin'

My input: 59 3024x3024 images
Could you help? Thanks!

**Comment by ibtehajali67** [comment]
what is the solution of it
