### ISSUE TITLE
FileNotFoundError on running imgs2poses.py

### ISSUE THREAD

**Issue by Wasp3r** [Fyusion/LLFF#71]
Hello everyone,

I have a problem to perform img2poses.py. It's throwing exception as below. I'm trying it on windows using anaconda. Strange this is, I've managed to check and run problematic command alone and it worked. The command is:

```
colmap feature_extractor --database_path demo\database.db --image_path demo\images --ImageReader.single_camera 1
```

Error message

```
Traceback (most recent call last):
  File "D:\nvdiffrec\LLFF-master\imgs2poses.py", line 18, in <module>
    gen_poses(args.scenedir, args.match_type)
  File "D:\nvdiffrec\LLFF-master\llff\poses\pose_utils.py", line 268, in gen_poses
    run_colmap(basedir, match_type)
  File "D:\nvdiffrec\LLFF-master\llff\poses\colmap_wrapper.py", line 35, in run_colmap
    feat_output = ( subprocess.check_output(feature_extractor_args, universal_newlines=True) )
  File "C:\Users\Admin\anaconda3\envs\llff\lib\subprocess.py", line 420, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
  File "C:\Users\Admin\anaconda3\envs\llff\lib\subprocess.py", line 501, in run
    with Popen(*popenargs, **kwargs) as process:
  File "C:\Users\Admin\anaconda3\envs\llff\lib\subprocess.py", line 966, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "C:\Users\Admin\anaconda3\envs\llff\lib\subprocess.py", line 1435, in _execute_child
    hp, ht, pid, tid = _winapi.CreateProcess(executable, args,
FileNotFoundError: [WinError 2] The system cannot find the file specified
```

**Comment by mexicantexan** [comment]
Make sure you have `colmap` installed and added to your environment variables

[https://github.com/colmap/colmap/releases/tag/3.7](https://github.com/colmap/colmap/releases/tag/3.7)

**Comment by raying777** [comment]
> 
hi~, how to added that to my environment variables?

> Hello everyone,
> 
> I have a problem to perform img2poses.py. It's throwing exception as below. I'm trying it on windows using anaconda. Strange this is, I've managed to check and run problematic command alone and it worked. The command is:
> 
> ```
> colmap feature_extractor --database_path demo\database.db --image_path demo\images --ImageReader.single_camera 1
> ```
> 
> Error message
> 
> ```
> Traceback (most recent call last):
>   File "D:\nvdiffrec\LLFF-master\imgs2poses.py", line 18, in <module>
>     gen_poses(args.scenedir, args.match_type)
>   File "D:\nvdiffrec\LLFF-master\llff\poses\pose_utils.py", line 268, in gen_poses
>     run_colmap(basedir, match_type)
>   File "D:\nvdiffrec\LLFF-master\llff\poses\colmap_wrapper.py", line 35, in run_colmap
>     feat_output = ( subprocess.check_output(feature_extractor_args, universal_newlines=True) )
>   File "C:\Users\Admin\anaconda3\envs\llff\lib\subprocess.py", line 420, in check_output
>     return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
>   File "C:\Users\Admin\anaconda3\envs\llff\lib\subprocess.py", line 501, in run
>     with Popen(*popenargs, **kwargs) as process:
>   File "C:\Users\Admin\anaconda3\envs\llff\lib\subprocess.py", line 966, in __init__
>     self._execute_child(args, executable, preexec_fn, close_fds,
>   File "C:\Users\Admin\anaconda3\envs\llff\lib\subprocess.py", line 1435, in _execute_child
>     hp, ht, pid, tid = _winapi.CreateProcess(executable, args,
> FileNotFoundError: [WinError 2] The system cannot find the file specified
> ```

Hello, can you tell me how you solved this problem

**Comment by YHXYJ** [comment]
> Hello everyone,
> 
> I have a problem to perform img2poses.py. It's throwing exception as below. I'm trying it on windows using anaconda. Strange this is, I've managed to check and run problematic command alone and it worked. The command is:
> 
> ```
> colmap feature_extractor --database_path demo\database.db --image_path demo\images --ImageReader.single_camera 1
> ```
> 
> Error message
> 
> ```
> Traceback (most recent call last):
>   File "D:\nvdiffrec\LLFF-master\imgs2poses.py", line 18, in <module>
>     gen_poses(args.scenedir, args.match_type)
>   File "D:\nvdiffrec\LLFF-master\llff\poses\pose_utils.py", line 268, in gen_poses
>     run_colmap(basedir, match_type)
>   File "D:\nvdiffrec\LLFF-master\llff\poses\colmap_wrapper.py", line 35, in run_colmap
>     feat_output = ( subprocess.check_output(feature_extractor_args, universal_newlines=True) )
>   File "C:\Users\Admin\anaconda3\envs\llff\lib\subprocess.py", line 420, in check_output
>     return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
>   File "C:\Users\Admin\anaconda3\envs\llff\lib\subprocess.py", line 501, in run
>     with Popen(*popenargs, **kwargs) as process:
>   File "C:\Users\Admin\anaconda3\envs\llff\lib\subprocess.py", line 966, in __init__
>     self._execute_child(args, executable, preexec_fn, close_fds,
>   File "C:\Users\Admin\anaconda3\envs\llff\lib\subprocess.py", line 1435, in _execute_child
>     hp, ht, pid, tid = _winapi.CreateProcess(executable, args,
> FileNotFoundError: [WinError 2] The system cannot find the file specified
> ```

Hello, I have the same problem. Can you tell me how you solved this problem. Thinks!
