### ISSUE TITLE
UnicodeDecodeError

### ISSUE THREAD

**Issue by codecy-12** [Fyusion/LLFF#76]
when I run imgs2poses.py, I got this error:

['points3D.bin', 'cameras.bin', 'images.bin']
Don't need to run COLMAP
Post-colmap
Cameras 5
Traceback (most recent call last):
  File "/data1/w/LLFF-master/imgs2poses.py", line 19, in <module>
    gen_poses(args.scenedir, args.match_type)
  File "/data1/w/LLFF-master/llff/poses/pose_utils.py", line 276, in gen_poses
    poses, pts3d, perm = load_colmap_data(basedir)
  File "/data1/w/LLFF-master/llff/poses/pose_utils.py", line 26, in load_colmap_data
    imdata = read_model.read_images_binary(imagesfile)
  File "/data1/w/LLFF-master/llff/poses/colmap_read_model.py", line 187, in read_images_binary
    image_name += current_char.decode("utf-8")
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xeb in position 0: unexpected end of data

**Comment by SaadatKhan** [comment]
did you check your image file names?  just don't include any special character.
