### ISSUE TITLE
IndexError: index -1 is out of bounds for axis 0 with size 0

### ISSUE THREAD

**Issue by fanzz1208** [Fyusion/LLFF#83]
Points (1, 3) Visibility (1, 19)
Depth stats 199.47634294350073 205.96847091521676 202.9606774417559
Traceback (most recent call last):
  File "imgs2poses.py", line 19, in <module>
    gen_poses(args.scenedir, args.match_type)
  File "/workspace/LLFF/llff/poses/pose_utils.py", line 281, in gen_poses
    save_poses(basedir, poses, pts3d, perm)
  File "/workspace/LLFF/llff/poses/pose_utils.py", line 87, in save_poses
    close_depth, inf_depth = np.percentile(zs, .1), np.percentile(zs, 99.9)
  File "<__array_function__ internals>", line 6, in percentile
  File "/opt/conda/lib/python3.7/site-packages/numpy/lib/function_base.py", line 3868, in percentile
    a, q, axis, out, overwrite_input, interpolation, keepdims)
  File "/opt/conda/lib/python3.7/site-packages/numpy/lib/function_base.py", line 3988, in _quantile_unchecked
    interpolation=interpolation)
  File "/opt/conda/lib/python3.7/site-packages/numpy/lib/function_base.py", line 3564, in _ureduce
    r = func(a, **kwargs)
  File "/opt/conda/lib/python3.7/site-packages/numpy/lib/function_base.py", line 4098, in _quantile_ureduce_func
    n = np.isnan(ap[-1])
IndexError: index -1 is out of bounds for axis 0 with size 0

How to solve it？？？

**Comment by Zhaoyibinn** [comment]
Have you solved this problem？

**Comment by ehatami65** [comment]
I got the same error, have you figured that out?
